# Generated by Django 4.2.27 on 2026-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ic_number',
            field=models.CharField(blank=True, help_text='IC Number without dashes', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name as per IC', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_registration',
            field=models.CharField(blank=True, help_text='SSM/ROC Number', max_length=100, null=True),
        ),
    ]
