# Generated by Django 4.2.27 on 2026-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ic_number_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='farm_details_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='farms/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='farm_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='farms/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='haccp_certificate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='halal_certificate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mygap_certificate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_certificate',
            field=models.CharField(blank=True, help_text='MESTI, etc.', max_length=200, null=True),
        ),
    ]
