# Generated by Django 4.2.27 on 2026-02-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('aquaculture', 'Aquaculture'), ('seafoods', 'Seafoods'), ('agro_processed', 'Agro-Processed'), ('courses', 'Courses Offered'), ('tools_rent', 'Tools for Rent'), ('jobs', 'Jobs in Agro')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('johor', 'Johor'), ('kedah', 'Kedah'), ('kelantan', 'Kelantan'), ('melaka', 'Melaka'), ('negeri_sembilan', 'Negeri Sembilan'), ('pahang', 'Pahang'), ('penang', 'Penang'), ('perak', 'Perak'), ('perlis', 'Perlis'), ('sabah', 'Sabah'), ('sarawak', 'Sarawak'), ('selangor', 'Selangor'), ('terengganu', 'Terengganu'), ('kuala_lumpur', 'Kuala Lumpur'), ('labuan', 'Labuan'), ('putrajaya', 'Putrajaya')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='listings/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
