# Generated by Django 4.2.27 on 2026-02-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_months',
            field=models.CharField(blank=True, help_text="Comma-separated month numbers (1-12) or 'always' for year-round availability", max_length=255),
        ),
    ]
